@server=http://localhost:4004

### POST Create a new employee
POST {{server}}/employee/Employees
Content-Type: application/json
Accept: application/json
//Authorization: Basic Q2hpdHRpOnVzZXI=
Authorization: Basic EMPAdmin:user

{
  "empId": "EMP018",
  "firstName": "CAPM",
  "lastName": "BTP",
  "email": "CAPM.BTP@gmail1.com",
  "department": "IT",
  "salary": 75000
}

### Update an employee
PATCH {{server}}/employee/Employees('bae2a62a-0257-486f-ac1f-df48b7a0d58b')
Content-Type: application/json
Accept: application/json

{
   "email": "Peter@gmail.com"  
}

### Delete an employee
DELETE {{server}}/employee/Employees('a78d8b6c-f673-4507-8f88-ef34295bfe55')
Content-Type: application/json
Accept: application/json
Authorization: Basic EMPManager:user


### Get all employees
GET {{server}}/employee/Employees
Authorization: Basic Chitti:user
Content-Type: application/json
Accept: application/json

//Authorization: Basic Q2hpdHRpOnVzZXI=
### Get an employee
GET {{server}}/employee/Employees('aa1b7070-b9d9-441c-9cc5-0601c3bdf1d4')

###Filter -Employees in IT department:

GET {{server}}/employee/Employees?$filter=department eq 'IT'

### Sort - Sort by salary:
GET {{server}}/employee/Employees?$orderby=salary desc

###Top Records
GET {{server}}/employee/Employees?$orderby=ID & $top=5

###Skip Records
GET {{server}}/employee/Employees?$skip=5

###Select Specific Fields
GET {{server}}/employee/Employees?$select=empId,firstName,salary


###Search Employee
GET {{server}}/employee/Employees?$search=John

###Multiple Conditions
GET {{server}}/employee/Employees?$filter=salary gt 50000 and department eq 'IT'


### Create Employee with Composition

POST {{server}}/employee/Employees
Content-Type: application/json
Accept: application/json

{
    "empId":"EMP018",
    "firstName":"John",
    "lastName":"Doe",
    "email":"john@gmail.com",
    "department":"IT",
    "salary":80000,
    "addresses":[
        {
            "houseNo":"12A",
            "street":"MG Road",
            "city":"Bangalore",
            "state":"Karnataka",
            "country":"India",
            "pincode":"560001"
        },
        {
            "houseNo":"20B",
            "street":"Brigade Road",
            "city":"Bangalore",
            "state":"Karnataka",
            "country":"India",
            "pincode":"560025"
        }
    ]
}


### Read Employee with Addresses
GET {{server}}/employee/Employees?$expand=addresses
Authorization: Basic Q2hpdHRpOnVzZXI=
Content-Type: application/json
Accept: application/json

###Create a Department
POST {{server}}/employee/Departments
Content-Type: application/json

{
    "deptId":"D001",
    "deptName":"Information Technology"
}

###Create an Employee Associated with the Department
POST {{server}}/employee/Employees
Content-Type: application/json

{
    "empId":"EMP001",
    "firstName":"John",
    "lastName":"Doe",
    "email":"john@gmail.com",
    "salary":75000,

    "department":"5a0858ad-0f1f-4f0a-a327-306da4fc1232"
}

###Read Employee with Department
GET {{server}}/employee/Employees?$expand=departments

###Read Department with Employees
GET {{server}}/employee/Departments?$expand=employees

###Delete an Employee
DELETE {{server}}/employee/Employees('eacf4afc-82ce-4971-87df-c7291bd2240e')


####Get Annual Salary of an Employee
GET {{server}}/employee/getAnnualSalary(ID = '5a79c537-1381-4784-a142-ad52612fe3c9')

### Get Employee Count
GET {{server}}/employee/getEmployeeCount()

### Increase Salary of an Employee
POST {{server}}/employee/increaseSalary
Content-Type: application/json

{
    "ID":"aa1b7070-b9d9-441c-9cc5-0601c3bdf1d4",
    "percentage":10
}
#### Promote an Employee

POST {{server}}/employee/promoteEmployee
Content-Type: application/json

{
    "ID":"aa1b7070-b9d9-441c-9cc5-0601c3bdf1d4",
    "department":"Management"
}


